//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serializer_Test.ICarService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice", ConfigurationName="ICarService.ICarServicePortType")]
    public interface ICarServicePortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:traceStolenProducts", ReplyAction="urn:traceStolenProductsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Serializer_Test.ICarService.traceStolenProductsResponse traceStolenProducts(Serializer_Test.ICarService.traceStolenProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:traceStolenProducts", ReplyAction="urn:traceStolenProductsResponse")]
        System.Threading.Tasks.Task<Serializer_Test.ICarService.traceStolenProductsResponse> traceStolenProductsAsync(Serializer_Test.ICarService.traceStolenProductsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:traceStolenParts", ReplyAction="urn:traceStolenPartsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Serializer_Test.ICarService.traceStolenPartsResponse traceStolenParts(Serializer_Test.ICarService.traceStolenPartsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:traceStolenParts", ReplyAction="urn:traceStolenPartsResponse")]
        System.Threading.Tasks.Task<Serializer_Test.ICarService.traceStolenPartsResponse> traceStolenPartsAsync(Serializer_Test.ICarService.traceStolenPartsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:traceStolenCar", ReplyAction="urn:traceStolenCarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Serializer_Test.ICarService.traceStolenCarResponse traceStolenCar(Serializer_Test.ICarService.traceStolenCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:traceStolenCar", ReplyAction="urn:traceStolenCarResponse")]
        System.Threading.Tasks.Task<Serializer_Test.ICarService.traceStolenCarResponse> traceStolenCarAsync(Serializer_Test.ICarService.traceStolenCarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="traceStolenProducts", WrapperNamespace="http://webservice", IsWrapped=true)]
    public partial class traceStolenProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args0;
        
        public traceStolenProductsRequest() {
        }
        
        public traceStolenProductsRequest(string args0) {
            this.args0 = args0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="traceStolenProductsResponse", WrapperNamespace="http://webservice", IsWrapped=true)]
    public partial class traceStolenProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public traceStolenProductsResponse() {
        }
        
        public traceStolenProductsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="traceStolenParts", WrapperNamespace="http://webservice", IsWrapped=true)]
    public partial class traceStolenPartsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args0;
        
        public traceStolenPartsRequest() {
        }
        
        public traceStolenPartsRequest(string args0) {
            this.args0 = args0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="traceStolenPartsResponse", WrapperNamespace="http://webservice", IsWrapped=true)]
    public partial class traceStolenPartsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public traceStolenPartsResponse() {
        }
        
        public traceStolenPartsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="traceStolenCar", WrapperNamespace="http://webservice", IsWrapped=true)]
    public partial class traceStolenCarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args0;
        
        public traceStolenCarRequest() {
        }
        
        public traceStolenCarRequest(string args0) {
            this.args0 = args0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="traceStolenCarResponse", WrapperNamespace="http://webservice", IsWrapped=true)]
    public partial class traceStolenCarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public traceStolenCarResponse() {
        }
        
        public traceStolenCarResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICarServicePortTypeChannel : Serializer_Test.ICarService.ICarServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarServicePortTypeClient : System.ServiceModel.ClientBase<Serializer_Test.ICarService.ICarServicePortType>, Serializer_Test.ICarService.ICarServicePortType {
        
        public CarServicePortTypeClient() {
        }
        
        public CarServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Serializer_Test.ICarService.traceStolenProductsResponse Serializer_Test.ICarService.ICarServicePortType.traceStolenProducts(Serializer_Test.ICarService.traceStolenProductsRequest request) {
            return base.Channel.traceStolenProducts(request);
        }
        
        public string traceStolenProducts(string args0) {
            Serializer_Test.ICarService.traceStolenProductsRequest inValue = new Serializer_Test.ICarService.traceStolenProductsRequest();
            inValue.args0 = args0;
            Serializer_Test.ICarService.traceStolenProductsResponse retVal = ((Serializer_Test.ICarService.ICarServicePortType)(this)).traceStolenProducts(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Serializer_Test.ICarService.traceStolenProductsResponse> Serializer_Test.ICarService.ICarServicePortType.traceStolenProductsAsync(Serializer_Test.ICarService.traceStolenProductsRequest request) {
            return base.Channel.traceStolenProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Serializer_Test.ICarService.traceStolenProductsResponse> traceStolenProductsAsync(string args0) {
            Serializer_Test.ICarService.traceStolenProductsRequest inValue = new Serializer_Test.ICarService.traceStolenProductsRequest();
            inValue.args0 = args0;
            return ((Serializer_Test.ICarService.ICarServicePortType)(this)).traceStolenProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Serializer_Test.ICarService.traceStolenPartsResponse Serializer_Test.ICarService.ICarServicePortType.traceStolenParts(Serializer_Test.ICarService.traceStolenPartsRequest request) {
            return base.Channel.traceStolenParts(request);
        }
        
        public string traceStolenParts(string args0) {
            Serializer_Test.ICarService.traceStolenPartsRequest inValue = new Serializer_Test.ICarService.traceStolenPartsRequest();
            inValue.args0 = args0;
            Serializer_Test.ICarService.traceStolenPartsResponse retVal = ((Serializer_Test.ICarService.ICarServicePortType)(this)).traceStolenParts(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Serializer_Test.ICarService.traceStolenPartsResponse> Serializer_Test.ICarService.ICarServicePortType.traceStolenPartsAsync(Serializer_Test.ICarService.traceStolenPartsRequest request) {
            return base.Channel.traceStolenPartsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Serializer_Test.ICarService.traceStolenPartsResponse> traceStolenPartsAsync(string args0) {
            Serializer_Test.ICarService.traceStolenPartsRequest inValue = new Serializer_Test.ICarService.traceStolenPartsRequest();
            inValue.args0 = args0;
            return ((Serializer_Test.ICarService.ICarServicePortType)(this)).traceStolenPartsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Serializer_Test.ICarService.traceStolenCarResponse Serializer_Test.ICarService.ICarServicePortType.traceStolenCar(Serializer_Test.ICarService.traceStolenCarRequest request) {
            return base.Channel.traceStolenCar(request);
        }
        
        public string traceStolenCar(string args0) {
            Serializer_Test.ICarService.traceStolenCarRequest inValue = new Serializer_Test.ICarService.traceStolenCarRequest();
            inValue.args0 = args0;
            Serializer_Test.ICarService.traceStolenCarResponse retVal = ((Serializer_Test.ICarService.ICarServicePortType)(this)).traceStolenCar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Serializer_Test.ICarService.traceStolenCarResponse> Serializer_Test.ICarService.ICarServicePortType.traceStolenCarAsync(Serializer_Test.ICarService.traceStolenCarRequest request) {
            return base.Channel.traceStolenCarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Serializer_Test.ICarService.traceStolenCarResponse> traceStolenCarAsync(string args0) {
            Serializer_Test.ICarService.traceStolenCarRequest inValue = new Serializer_Test.ICarService.traceStolenCarRequest();
            inValue.args0 = args0;
            return ((Serializer_Test.ICarService.ICarServicePortType)(this)).traceStolenCarAsync(inValue);
        }
    }
}
